#!/usr/bin/env python

from __future__ import print_function

import events as e

def main(istream, ostream):
    for line in istream:
        event = e.decode_event(line)
        print(event, file=ostream)

if __name__ == "__main__":
    import sys

    istream = sys.stdin
    ostream = sys.stdout

    main(istream, ostream)
